### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by BaiYunpeng1949** [DiLi-Lab/ScanDL#10]
Hi, thank you for the wonderful work!

For quicker replications, do you mind sharing some pretrained models/weights as *.zip?

**Comment by BaiYunpeng1949** [comment]
As I am trying to replicate your results,

for other baseline models, such as EZReader, SWIFT; did you code yourselves or use exisiting simulations? Do you mind pointinng me out where to find them?

Thank you!

**Comment by SiQube** [comment]
hi @BaiYunpeng1949,

thank you for your interest in scandl. the baselines can be found here:

- [Eyettention](https://github.com/aeye-lab/eyettention)
- [SWIFT](https://osf.io/xdkwq/)
- [E-Z Reader](http://www.erikdreichle.com/downloads.html)

we adjusted the models to our datasets -- simulating cloze probabilities using BERT and predictability using GPT-2. some datasets also have those measures within their eye movement respositories.

**Comment by BaiYunpeng1949** [comment]
Thank you for the response! And do you happen to have available pretrained ScanDL models?

**Comment by lenabolliger** [comment]
Hi @BaiYunpeng1949 , there is not 'the model' but there are model weights for each training fold in each of the evaluation settings as described in the paper, i.e., many different sets of weights. we are planning on releasing a fully pre-trained model next year.
