### ISSUE TITLE
Issue with the get_zuco_data.sh file

### ISSUE THREAD

**Issue by nisar2** [DiLi-Lab/ScanDL#7]
Hello,

I am trying to get the repository up on and running on my machine and was having some trouble with using the get_zuco_data.sh file to work.When I run this script, I get the following error: "scripts/get_zuco_data.sh: line 14: syntax error near unexpected token `osfclient'". Any help about overcoming this would be greatly appreciated.

Thanks in advance!

**Comment by SiQube** [comment]
hi -- thanks for pointing the issue out PR #8  resolves this issue -- please try again.

**Comment by nisar2** [comment]
I can confirm that it works now. Thank you!
