### ISSUE TITLE
the dataset

### ISSUE THREAD

**Issue by foxquan** [DiLi-Lab/ScanDL#9]
I can't download the celer,so I use zuco to train. can you tell  how to set the 'PATH_TO_FIX','PATH_TO_IA' and 'SUB_METADATA_PATH'   in the CONSTANT.py

**Comment by SiQube** [comment]
dear @foxquan, 

you have to set all those paths to the directory where you data is. e.g. if you saved the zuco data in the folder `zuco` on root, just set the `zuco_data_path = zuco`.

if you do not want to adjust the paths in config, use the bash scripts in the `scripts` folder. especially [`get_zuco_data.sh`](https://github.com/DiLi-Lab/ScanDL/blob/main/scripts/get_zuco_data.sh)

note, in this paper (and thus repository), we were only concerned with inference on zuco and not with training on zuco. to train on zuco you have to adjust the training script.
